dist: xenial
language: php
php:
  - 7.4.0
  - 7.4.1
  - 7.4.2
  - 7.4
cache:
  files:
    - ./.php_cs.cache
  directories:
    - ./vendor/
before_script:
  - phpenv config-rm xdebug.ini
install:
  - travis_retry composer install --no-interaction --no-suggest --prefer-source
script:
  - composer run tests
matrix:
  fast_finish: true
