language: php
dist: bionic
php:
  - 7.4.0
  - 7.4.1
  - 7.4.2
  - 7.4
matrix:
  include:
    - php: 7.4
      env:
        - psalm=yes
  fast_finish: true
cache:
  files:
    - ./.php_cs.cache
  directories:
    - $HOME/.composer/cache
    - ./psalm/cache
before_script:
  - phpenv config-rm xdebug.ini
install:
  - travis_retry composer install --no-interaction --no-suggest --prefer-source
  - if [[ "$psalm" != "yes" ]]; then composer update --dry-run roave/security-advisories; fi
script:
  - if [[ "$psalm" = "yes" ]]; then ./vendor/bin/psalm --shepherd --show-info=false --diff --diff-methods; fi
  - if [[ "$psalm" != "yes" ]]; then composer run static-analysis; fi
